jobs:
  build:
    "runs-on": "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - id: "setup-haskell-cabal"
      uses: "haskell-actions/setup@v2"
      with:
        "cabal-version": '3.10'
        "enable-stack": false
        "ghc-version": '9.4.7'
    - name: Update Hackage repository
      run: cabal update
    - uses: "actions/cache@v3"
      with:
        key: "${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ hashFiles('cabal.project.freeze') }}"
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
    - name: Install dhall
      run: cabal install dhall
    - name: "Install dhall-to-yaml &c."
      run: "cabal install dhall-yaml"
    - name: Check Dhall
      run: |
        export PATH=$HOME/.cabal/bin:$PATH
        dhall --file haskell-ci.dhall
        dhall --file self-ci.dhall
    - name: Check Dhall can be converted to YAML
      run: |
        export PATH=$HOME/.cabal/bin:$PATH
        dhall-to-yaml-ng --file self-ci.dhall
        dhall-to-yaml-ng --file ci.dhall
name: Dhall CI
'on':
- push
- pull_request
